# Generated by Django 3.0.6 on 2020-10-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0002_auto_20201017_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='bio',
            new_name='additional_experience',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='company',
            new_name='specialization1',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='specification1',
            new_name='specialization2',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='specification2',
            new_name='specialization3',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='specification3',
            new_name='specialization4',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='specification4',
            new_name='workplace1',
        ),
        migrations.AddField(
            model_name='experience',
            name='workplace2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='workplace3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='workplace4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
