# Generated by Django 3.0.6 on 2020-10-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0011_auto_20201017_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='additional_experience',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='rank2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='rank3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='rank4',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='specialization2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='specialization3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='specialization4',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='workplace2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='workplace3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='workplace4',
        ),
    ]
