# Generated by Django 3.0.6 on 2020-10-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0012_auto_20201017_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='heading',
            field=models.CharField(default='Python', max_length=30),
            preserve_default=False,
        ),
    ]
